package com.green.jaeyoon.goodmorning.domain;

import jakarta.persistence.*;
import lombok.*;

//-------
//p445
//-------
@Entity //Marks the class as a database entity(table)
@Builder //Allows building objects in a flexible way.
@AllArgsConstructor //Creates a constructor with all fields
@NoArgsConstructor // Creates an empty constructor
@Getter // Generates a getter methods for all fields
@ToString // Creates a toString() method for easy printing
@Table( //creates a table called tbl_cart -> mainly searches with user email
        name = "tbl_cart",
        indexes = { @Index(name="idx_cart_email", columnList = "member_owner")}
        //creates index in the table through @Index
)
//====================================================================
//Cart entity sets the relationship to the specific user's information.
//====================================================================

public class Cart { // this is an entity class representing a cart table in the database.

    @Id // Marks the field as the primary key of the entity.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //Specified that the primary key value should be automatically generated by the database.
    private Long cno; //-> Primary key, auto generated

    @OneToOne // Defines a one-to-one relationship with another entity.
    @JoinColumn(name="member_owner")// Specified the foreign key column ("member_owner')
    private Member owner; // A reference to the Member entity representing the cart's owner.
}
